#!/usr/bin/env ruby
#filename: canned_response_generator.rb
#date: 26/Dec 2019
#description: provide canned responses to customers when they ask about reports.
#
#
proceedure_tables = [
	 {"vulerablitity" => "SSL Version 2 and 3 Protocol Detection", "fix" =>
   {"Fix"=> "Edit SSL Cyphers", "Filename:" => "/etc/httpd/conf.d/z-ecf-settings.conf", "Baseline:" => "SSLProtocol all -SSLv2 -SSLv3 -TLSv1"}
	},
  {"vulerablitity" => "Spring Framework 4.3.x < / 5.0.x < 5.05 Remote Code Execution with spring-messageing (CVE-2018-1280)", "fix" =>
   {"This is not a court responsiblity. Someone will address this in the near future."=>"Action required: none."}
	 },
  {"vulerablitity" => "Oracle Java SE 1.7.0_241/ 1.8.0_231/ 1.11.0_5 / 1.13.0_1 Multiple Vulerablities (Oct 2019 CPU) (Unix)", "fix" =>
   {"This is not a customer responsiblity. The someone will address this in the near future."=>"Action required: none."}
  },
  {"vulerablitity" => "RHEL 6 : sudo (RHSA-2019:3755) ", "fix" =>
   {"This is not a customer responsiblity. Someone will address this in the near future."=>"Action required: none."}
  },
  {"vulerablitity" => "SSL Certificiate Signed Using a Weak Hashing Alogrithim", "fix" =>
   {"This is not a customer responsiblity. Someone will address this in the near future."=>"Action required: none."}
  },
  {"vulerablitity" => "RHEL 6 : firefox (RHSA-2019:2694)", "fix" =>
   {"This is not a customer responsiblity. Someone will address this in the near future."=>"Action required: none."}
  },
  {"vulerablitity" => "SSL CA Certificate Cannot be trusted.", "fix" =>
   {"This is not a customer responsiblity. Someone will address this in the near future."=>"Action required: none."}
  },
  {"vulerablitity" => "SSLv3 Padding Oracle on Downgraded Legacy Enryption Vulernerablity(POODLE)", "fix" =>
   {"Fix"=> "Edit SSL Cyphers", "Filename:" => "/etc/httpd/conf.d/z-ecf-settings.conf", "Baseline:" => "SSLProtocol all -SSLv2 -SSLv3 -TLSv1"}
  },
  {"vulerablitity" => "SSH Weak Alogrithms Supported", "fix" =>
   {"Fix"=> "Edit SSH Cyphers", "Filename:" => "/etc/ssh/sshd_config", "Baseline:" => "Protocol 2 #only"}
  },
  {"vulerablitity" => "RHEL 6: java-1.8.0-oracle (RHSA-2018:3003)", "fix" =>
   {"This is not a customer responsiblity. Someone  will address this in the near future."=>"Action required: none."}
  },
  {"vulerablitity" => "RHEL 6: openssl (RHSA-2019-2471)", "fix" =>
   {"This is not a customer responsiblity. Someone will address this in the near future."=>"Action required: none."}
  },
  {"vulerablitity" => "RHEL 6/7 : ImageMagick (RHSA-2019:1237)", "fix" =>
   {"This is not a customer responsiblity. Someone will address this in the near future."=>"Action required: none."}
  },
  {"vulerablitity" => "SSL Medium Strength Ciphers Suites Supported (SWEET32)", "fix" =>
   {"Fix"=> "Court can safely remove 64-bit,112-bit,or 3DES encryption hashs", "Filename:" => "/etc/httpd/conf.d/z-ecf-settings.conf", "Baseline:" => "SSLCipherSuite ... (ask us) "}
  }

 ]

def menu_selection(proceedure_tables)
  puts "Please select a vulerablity #"
  proceedure_tables.each_with_index do |vulerablity, index|
    puts "#{index+1}: #{vulerablity["vulerablitity"]}"
  end
end

response_report=[]
menu_selection(proceedure_tables)

while input = gets do
   menu_selection(proceedure_tables) if response_report.length > 0
   if input =="\n"
      break
   end
   response_report.push(input)
end

puts "\n\n"
count=1
response_report.each do | user_input |
  puts "\n\n#{count}: " + proceedure_tables[user_input.to_i - 1]["vulerablitity"]
  proceedure_tables[user_input.to_i - 1]["fix"].each do |fix, proceedure|
	  puts "#{fix} #{proceedure}\n"
    count+=1
  end
end
